services:
  localstack:
    image: localstack/localstack:3.8
    container_name: ticket-app-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3,ses
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
